spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    url: ${DATA_BASE_URL:jdbc:mysql://localhost:3306/infuse?useSSL=false}
    username: ${DATABASE_USER:admin}
    password: ${DATA_BASE_PASSWORD:123}
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
          show_sql: true
          format_sql: true

#Flyway cofigs

flyway:
  url: ${DATA_BASE_URL:jdbc:mysql://localhost:3306/infuse?useSSL=false}
  schemas: ${DATABASE:infuse}
  user: ${DATA_BASE_USE:admin}
  password: ${DATA_BASE_PASSWORD:123}


---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---

percentual:
  cinco: ${PERCENTUAL_CINCO:0.05}
  dez: ${PERCENTUAL_DEZ:0.10}